name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1.4.0
      with:
        channel: 'beta'
    - name: Get dependencies
      run: flutter pub get

    - name: 'Flutter Format Check'
      run: flutter format --set-exit-if-changed --dry-run .

    - name: Run tests
      run: flutter test
